apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
  namespace: bigproject
  labels:
    app: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
  - port: 3000
    name: http
    targetPort: 3000
