apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: bigproject
  name: apigateway
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway
  targetCPUUtilizationPercentage: 100
