apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: bigproject
  name: apigateway-scaler
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
