apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bigproject
  name: apigateway
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${ENV_STAGE}-api-bigproject
    kubernetes.io/ingress.allow-http: 'false'
    networking.gke.io/managed-certificates: apigateway
spec:
  rules:
  - host: ${ENV_STAGE}.apigateway.bigproject.papasoleh.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /*
        backend:
          service:
            name: apigateway-svc
            port:
              number: 3000
