apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bigproject
  name: apigateway
  annotations:
    kubernetes.io/ingress.global-static-ip-name: apigateway
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: apigateway
spec:
  rules:
    - host: $HOST
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: apigateway
              port:
                number: 3000
